### ISSUE TITLE
How to prepare the data for experiments?

### ISSUE THREAD

**Issue by xiangyh9988** [zxwu/adv_cloak#1]
Hi, your work is very interesting and I want to reproduce the 'adversarial aloak' based on this repo.
I am confused about the data preparation. As mentioned in the paper, 
> We craft attack patches using the COCO dataset, which contains a total of 123,000 images. After removing images from the dataset that do not contain people, we then chose a random subset of 10, 000 images for training.

Can you share the script for spliting the images for training? It seems that the code just uses `coco_2014_train` and `coco_2014_valminusminival` (the following config file is used in `train.sh`). https://github.com/zxwu/adv_cloak/blob/6eda27deaedd0f4a5d89008b8f495df8a462ded8/configs/e2e_mask_rcnn_R_50_FPN_1x.yaml#L33 

Is the training data extracted from COCO 2014?

By the way, is there the code to attack YOLOv2 or YOLOv3 solely? I can only see YOLOv2 and YOLOv3 are attacked in the ensemble models.

Thank you in advance!

**Comment by zdaiot** [comment]
Have you solved this problem? 
I have the same doubts.

**Comment by zxwu** [comment]
Please see https://github.com/facebookresearch/maskrcnn-benchmark#perform-training-on-coco-dataset to prepare the dataset. 

We attack yolov2 and v3 based on https://github.com/ultralytics/yolov3, but the core part is in the patch/ folder.
